Update README.rst
Japanese-Accent-Circle/japanese-accent pull request #21
Opened 2021-02-28 03:16 UTC by zenkinsen

2021-02-28 14:18 UTC, CBenoit requested changes

2021-02-28 14:18 UTC, CBenoit commented on README.rst
> +註：アクセント核が異なる単語のみ示す。箸（は\\し）[1]　→　お箸（おは\\し）[2]　のようなアクセント核の変化を起こさない単語は除く。
```suggestion
注意：アクセント核が異なる単語のみ示す。箸（は\\し）[1]　→　お箸（おは\\し）[2]　のようなアクセント核の変化を起こさない単語は除く。
```
C'est peut-être mieux de mettre 注意 (ou 注) que le 旧字体 ?

2021-02-28 14:20 UTC, CBenoit commented on README.rst
> +* 頭高型　→　[0]。例：堂、神体
```suggestion
* 平板型　→　[2]。例：電話、駄賃、子、無用、足労
* 尾高型　→　[2]　例：寿司、捻り、零れ、沙汰
* 尾高型　→　[0]　例：花、店、心、成り
* 中高型　→　[0]　例：得意、墨付き、用達し
* 頭高型　→　[0]　例：堂、神体
```

Ça serait pas mieux sans le `。` ? On le met pas aux autres endroits non plus

2021-02-28 14:22 UTC, CBenoit commented on README.rst
> +* 脱〜（だ\\つ〜）例：脱炭素化、脱原発、脱グローバル化、脱漢籍
J'ai l'impression que pour celui là, ça va avoir tendence à très fortement faire ダ\ツ・〇〇… de façon indépendante, peut-être qu'il faudrait le mettre un peu à part des autres (à cause des 注意)

2021-02-28 15:57 UTC, CBenoit commented on README.rst
> +* 平板型　→　[2]。例：電話、駄賃、子、無用、足労
ご褒美 est assez fréquent je pense

2021-03-01 23:39 UTC, CBenoit commented on README.rst
> +* 尾高型　→　[2]。例：寿司、捻り、零れ、沙汰
On peut aussi rajouter
粉\\ [2] → お\\粉 [2]

2021-03-08 14:00 UTC, zenkinsen commented
Normalement là c'est bon pour les 注意, j'ai également rajouté 相〜 (ex. 相成る)

2021-03-08 15:41 UTC, CBenoit approved these changes
Merci ! :+1:

2021-03-08 15:41 UTC, merged